import runwayData from "../data/runways.json" with { type: "json" };

export interface Runway {
  designator: string;
  leIdent: string;
  heIdent: string;
  leHeadingDegT: number | null;
  heHeadingDegT: number | null;
  lengthFt: number | null;
  surface: string | null;
}

const byIcao = runwayData as Record<string, Runway[]>;

/** Static OurAirports-derived runway lookup — data generated by scripts/generate-runway-data.mjs. */
export function getRunways(icao: string): Runway[] {
  return byIcao[icao.toUpperCase()] ?? [];
}
