kind = "web"
previewPath = "/"
title = "AERO-SENTINEL"
version = "1.0.0"
id = "artifacts/aero-sentinel"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 21382

[services.development]
run = "pnpm --filter @workspace/aero-sentinel run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/aero-sentinel", "run", "build" ]
publicDir = "artifacts/aero-sentinel/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "21382"
BASE_PATH = "/"
